/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Runs `SELECT 1` against Postgres. Returns 503 if the database is unreachable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True when every dependency answered. */
                            ok: boolean;
                            /** @description Result of a `SELECT 1` against Postgres. */
                            db: boolean;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True when every dependency answered. */
                            ok: boolean;
                            /** @description Result of a `SELECT 1` against Postgres. */
                            db: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which sign-in methods this deployment supports
         * @description Lets a client hide a Google button that would not work.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Email + password sign-in is always available. */
                            password: boolean;
                            /** @description True only when GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET are configured. */
                            google: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        displayName?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            /** @description Send as `Authorization: Bearer <token>`. */
                            accessToken: string;
                            /** @description Opaque. Exchange at POST /auth/refresh; it rotates on every use. */
                            refreshToken: string;
                            /** @enum {string} */
                            tokenType: "Bearer";
                            /** @description Access token lifetime in seconds. */
                            expiresIn: number;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            /** @description Send as `Authorization: Bearer <token>`. */
                            accessToken: string;
                            /** @description Opaque. Exchange at POST /auth/refresh; it rotates on every use. */
                            refreshToken: string;
                            /** @enum {string} */
                            tokenType: "Bearer";
                            /** @description Access token lifetime in seconds. */
                            expiresIn: number;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new session
         * @description The presented token is revoked and replaced, so it cannot be reused.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            /** @description Send as `Authorization: Bearer <token>`. */
                            accessToken: string;
                            /** @description Opaque. Exchange at POST /auth/refresh; it rotates on every use. */
                            refreshToken: string;
                            /** @enum {string} */
                            tokenType: "Bearer";
                            /** @description Access token lifetime in seconds. */
                            expiresIn: number;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Idempotent. The access token remains valid until it expires.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a fresh email-verification link
         * @description Always 202, whether or not the address is registered and whether or not it is already verified. Issuing a new link invalidates any previous unused one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Always the same text, whether or not an account exists for that address. */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem an email-verification token
         * @description Marks the address verified and returns the updated user. Does not sign anyone in — the link may well be opened in a browser that has no session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password-reset link
         * @description Always 202, whether or not the address is registered. Issuing a new link invalidates any previous unused one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Always the same text, whether or not an account exists for that address. */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a reset token
         * @description Revokes every existing session on success, so the client must sign in again with the new password. Returns 204 rather than a session for that reason.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Google sign-in
         * @description Redirects to Google. When the server has no Google credentials this redirects to OAUTH_SUCCESS_REDIRECT with `?error=not-configured`, or returns 501 when that is unset — call `GET /auth/providers` first to find out.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google sign-in callback
         * @description Exchanges the authorization code for a Recogno session. When OAUTH_SUCCESS_REDIRECT is set both outcomes redirect there — success with `accessToken`/`refreshToken`, failure with `error` (a stable code) and `error_description`. With it unset the session comes back as JSON and failures keep their status codes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                            /** @description Send as `Authorization: Bearer <token>`. */
                            accessToken: string;
                            /** @description Opaque. Exchange at POST /auth/refresh; it rotates on every use. */
                            refreshToken: string;
                            /** @enum {string} */
                            tokenType: "Bearer";
                            /** @description Access token lifetime in seconds. */
                            expiresIn: number;
                        };
                    };
                };
                /** @description Default Response */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                email: string;
                                displayName: string | null;
                                avatarUrl: string | null;
                                emailVerified: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session for this account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drill/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a problem to recognise
         * @description Returns the statement and constraints only. The ground-truth pattern and the tell are withheld until the guess is submitted.
         *
         *     Prefers an SRS card that is due, then a problem never seen, then the soonest-due card.
         *
         *     Pass `?deckId=` to restrict selection to one deck (system or the caller’s own); omit it to search across every deck visible to the caller, as before.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Scope to one deck (system or the caller’s own). Omit to search across every deck visible to the caller, as before. */
                    deckId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            problem: {
                                id: number;
                                slug: string;
                                title: string;
                                statement: string | null;
                                constraints: string | null;
                                sourceUrl: string | null;
                                difficulty: ("easy" | "medium" | "hard") | null;
                            };
                            /**
                             * @description Which branch supplied this problem: a card that is due, a problem never seen, or the soonest-due card when nothing is due yet.
                             * @enum {string}
                             */
                            source: "due" | "unseen" | "review-ahead";
                            /** @description When the card fell due. Null if this problem is new to the user. */
                            dueAt: string | null;
                            /** @description The full taxonomy to choose from. Reveals nothing about the answer. */
                            patternOptions: {
                                id: number;
                                /** @example sliding-window */
                                slug: string;
                                /** @example Sliding Window */
                                name: string;
                                /**
                                 * @description Study grouping. Group the picker by this — there are ~80 patterns.
                                 * @example Two Pointers
                                 */
                                category: string;
                            }[];
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drill/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a guess and advance the schedule
         * @description Grades correctness, speed and rationale, combines them into a composite, maps that onto an FSRS rating, and upserts the SRS card. Reveals the tell in the response.
         *
         *     A wrong guess cannot exceed the Hard band however fast or well argued it was, and a correct guess with no real reasoning lands there too.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        problemId: number;
                        /** @description One or more `id` values from `patternOptions`. Use this when a problem is a fair read as more than one pattern. */
                        guessedPatternIds?: number[];
                        /** @description One or more `slug` values from `patternOptions`, instead of ids. */
                        guessedPatternSlugs?: string[];
                        /** @description Single-guess shorthand, kept for existing clients. */
                        guessedPatternId?: number;
                        /** @description Why the learner thinks it is that pattern. Graded by Gemini. */
                        rationaleText: string;
                        /** @description Seconds from seeing the problem to guessing. Drives the speed score. */
                        timeTakenSeconds: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            attemptId?: string | null;
                            /** @description True when any guess exactly matched any accepted pattern. */
                            correct: boolean;
                            /** @description The first guess. See `guessedPatterns` for all of them. */
                            guessedPattern: {
                                id: number;
                                /** @example sliding-window */
                                slug: string;
                                /** @example Sliding Window */
                                name: string;
                                /**
                                 * @description Study grouping. Group the picker by this — there are ~80 patterns.
                                 * @example Two Pointers
                                 */
                                category: string;
                            };
                            /** @description Every pattern the learner named, in the order given. */
                            guessedPatterns: {
                                id: number;
                                /** @example sliding-window */
                                slug: string;
                                /** @example Sliding Window */
                                name: string;
                                /**
                                 * @description Study grouping. Group the picker by this — there are ~80 patterns.
                                 * @example Two Pointers
                                 */
                                category: string;
                            }[];
                            /** @description The canonical pattern; the one the tell explains. */
                            actualPattern: {
                                id: number;
                                /** @example sliding-window */
                                slug: string;
                                /** @example Sliding Window */
                                name: string;
                                /**
                                 * @description Study grouping. Group the picker by this — there are ~80 patterns.
                                 * @example Two Pointers
                                 */
                                category: string;
                                description: string;
                            };
                            /** @description Every pattern that counts as correct for this problem, including the canonical one. Naming any single one of these is full credit. */
                            acceptedPatterns: {
                                id: number;
                                /** @example sliding-window */
                                slug: string;
                                /** @example Sliding Window */
                                name: string;
                                /**
                                 * @description Study grouping. Group the picker by this — there are ~80 patterns.
                                 * @example Two Pointers
                                 */
                                category: string;
                            }[];
                            /** @description The pre-written "why this pattern" explanation. Null if none exists. */
                            tell: string | null;
                            /** @description Plain-language summary of the grade. */
                            explanation: string;
                            scores: {
                                /** @description 1 exact, 0.5 close family, 0 otherwise. */
                                correctness: number;
                                /** @description Linear from 1.0 at 0s to 0.0 at 90s. */
                                speed: number;
                                /** @description 1 yes, 0.5 partial, 0 no. */
                                rationale: number;
                                /** @description Weighted average: 0.5 / 0.2 / 0.3. */
                                composite: number;
                            };
                            rationale: {
                                /** @enum {string} */
                                verdict: "yes" | "partial" | "no";
                                /** @description False when Gemini was unreachable and the rationale scored neutrally. */
                                judged: boolean;
                            };
                            review: {
                                /**
                                 * @description The FSRS grade the composite mapped onto.
                                 * @enum {string}
                                 */
                                rating: "Again" | "Hard" | "Good" | "Easy";
                                previousDueAt: string | null;
                                /**
                                 * Format: date-time
                                 * @description When this problem comes back around.
                                 */
                                dueAt: string;
                                scheduledDays: number;
                                /** @description 0 New, 1 Learning, 2 Review, 3 Relearning. */
                                state: number;
                                reps: number;
                                lapses: number;
                                stability: number;
                                difficulty: number;
                            };
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drill/due-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the drill reps waiting
         * @description Drill-eligible cards whose due date has passed. For the badge that spans both flows, use `GET /review/due-count`.
         *
         *     Pass `?deckId=` to count only that deck, e.g. for a per-deck badge.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Scope to one deck (system or the caller’s own). Omit to search across every deck visible to the caller, as before. */
                    deckId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Cards due now — the "X reps due today" badge. */
                            dueCount: number;
                            /** @description When the soonest card falls due. Null if the user has no cards. */
                            nextDueAt: string | null;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List decks
         * @description Every system deck plus the caller's own, with problem counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            decks: {
                                id: number;
                                slug: string;
                                name: string;
                                description: string | null;
                                /** @description System decks hold the curated bank and are read-only. */
                                isSystem: boolean;
                                problemCount: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a personal deck */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** @description System decks hold the curated bank and are read-only. */
                            isSystem: boolean;
                            problemCount: number;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deck detail with its problems
         * @description Each problem carries the review `mode` it belongs to: `drill` when a curator gave it a pattern and a tell, `note` otherwise.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deckId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            slug: string;
                            name: string;
                            description: string | null;
                            /** @description System decks hold the curated bank and are read-only. */
                            isSystem: boolean;
                            problemCount: number;
                            problems: {
                                id: number;
                                slug: string;
                                title: string;
                                difficulty: ("easy" | "medium" | "hard") | null;
                                /** @enum {string} */
                                source: "curated" | "link" | "slug" | "text";
                                sourceUrl: string | null;
                                /**
                                 * @description Which review flow this problem uses. Decided by whether it has a pattern + tell.
                                 * @enum {string}
                                 */
                                mode: "drill" | "note";
                                dueAt: string | null;
                            }[];
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a problem and record the first attempt
         * @description Accepts a link, a slug or a free-text description, together with the note and solution.
         *
         *     Returns immediately with a queued submission: resolving the source and running the AI evaluation happen on the worker. Poll `GET /submissions/{id}` for progress.
         *
         *     Adding a problem that already exists in the deck records another attempt against it rather than failing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deckId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description A problem link, a slug, or a free-text description. */
                        input: string;
                        /**
                         * @description Force the interpretation of `input`. Auto-detected when omitted.
                         * @enum {string}
                         */
                        source?: "link" | "slug" | "text";
                        /** @description Overrides the title derived from the input. */
                        title?: string;
                        /** @description The approach taken and any issues faced. */
                        noteText: string;
                        /** @description Code, pseudocode or prose. Stored opaquely and never parsed. */
                        solutionText: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            problemId: number;
                            submission: {
                                id: string;
                                problemId: number;
                                problemTitle: string;
                                /** @enum {string} */
                                status: "queued" | "resolving-source" | "evaluating" | "awaiting-review" | "committed" | "failed";
                                failureReason: string | null;
                                noteText: string;
                                solutionText: string;
                                /** @description Only steps that genuinely run for this submission, in display order. */
                                stages: {
                                    /** @enum {string} */
                                    stage: "resolve-source" | "evaluate";
                                    /** @enum {string} */
                                    status: "pending" | "running" | "done" | "failed";
                                    position: number;
                                    detail: string | null;
                                    startedAt: string | null;
                                    finishedAt: string | null;
                                }[];
                                /** @description Null until the evaluate stage completes. */
                                evaluation: {
                                    /** @enum {string} */
                                    gradation: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                                    label: string;
                                    approachSummary: string;
                                    missed: string;
                                    optimizations: string;
                                    model: string | null;
                                } | null;
                                finalGradation: ("try-again" | "needs-work" | "not-bad" | "good-job" | "excellent") | null;
                                overridden: boolean;
                                committedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a submission
         * @description Returns the pipeline stages and, once evaluation finishes, the AI gradation and explanation. `status` reaches `awaiting-review` when it is ready to commit.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submissionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            problemId: number;
                            problemTitle: string;
                            /** @enum {string} */
                            status: "queued" | "resolving-source" | "evaluating" | "awaiting-review" | "committed" | "failed";
                            failureReason: string | null;
                            noteText: string;
                            solutionText: string;
                            /** @description Only steps that genuinely run for this submission, in display order. */
                            stages: {
                                /** @enum {string} */
                                stage: "resolve-source" | "evaluate";
                                /** @enum {string} */
                                status: "pending" | "running" | "done" | "failed";
                                position: number;
                                detail: string | null;
                                startedAt: string | null;
                                finishedAt: string | null;
                            }[];
                            /** @description Null until the evaluate stage completes. */
                            evaluation: {
                                /** @enum {string} */
                                gradation: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                                label: string;
                                approachSummary: string;
                                missed: string;
                                optimizations: string;
                                model: string | null;
                            } | null;
                            finalGradation: ("try-again" | "needs-work" | "not-bad" | "good-job" | "excellent") | null;
                            overridden: boolean;
                            committedAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{submissionId}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept or override the grade, and reschedule
         * @description The final gradation drives FSRS. Omit `gradation` to accept the AI's verdict; supply one to override it.
         *
         *     A submission whose evaluation failed can still be committed, but only with an explicit gradation — the learner self-grades rather than losing the attempt.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submissionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Overrides the AI's grade. Required when the evaluation failed.
                         * @enum {string}
                         */
                        gradation?: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submissionId: string;
                            /** @enum {string} */
                            finalGradation: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                            label: string;
                            overridden: boolean;
                            aiGradation: ("try-again" | "needs-work" | "not-bad" | "good-job" | "excellent") | null;
                            review: {
                                /** @enum {string} */
                                rating: "Again" | "Hard" | "Good" | "Easy";
                                previousDueAt: string | null;
                                /** Format: date-time */
                                dueAt: string;
                                scheduledDays: number;
                                state: number;
                                reps: number;
                                lapses: number;
                                stability: number;
                                difficulty: number;
                            };
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{problemId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attempt history for a problem
         * @description Newest first. Every encounter is its own record.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    problemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submissions: {
                                id: string;
                                problemId: number;
                                problemTitle: string;
                                /** @enum {string} */
                                status: "queued" | "resolving-source" | "evaluating" | "awaiting-review" | "committed" | "failed";
                                failureReason: string | null;
                                noteText: string;
                                solutionText: string;
                                /** @description Only steps that genuinely run for this submission, in display order. */
                                stages: {
                                    /** @enum {string} */
                                    stage: "resolve-source" | "evaluate";
                                    /** @enum {string} */
                                    status: "pending" | "running" | "done" | "failed";
                                    position: number;
                                    detail: string | null;
                                    startedAt: string | null;
                                    finishedAt: string | null;
                                }[];
                                /** @description Null until the evaluate stage completes. */
                                evaluation: {
                                    /** @enum {string} */
                                    gradation: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                                    label: string;
                                    approachSummary: string;
                                    missed: string;
                                    optimizations: string;
                                    model: string | null;
                                } | null;
                                finalGradation: ("try-again" | "needs-work" | "not-bad" | "good-job" | "excellent") | null;
                                overridden: boolean;
                                committedAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Record another attempt at a problem
         * @description The repeat-encounter path: a problem came due, the learner worked it again, and this is a fresh submission rather than an edit of the last one, so history is preserved.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    problemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The approach taken and any issues faced. */
                        noteText: string;
                        /** @description Code, pseudocode or prose. Stored opaquely and never parsed. */
                        solutionText: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            problemId: number;
                            problemTitle: string;
                            /** @enum {string} */
                            status: "queued" | "resolving-source" | "evaluating" | "awaiting-review" | "committed" | "failed";
                            failureReason: string | null;
                            noteText: string;
                            solutionText: string;
                            /** @description Only steps that genuinely run for this submission, in display order. */
                            stages: {
                                /** @enum {string} */
                                stage: "resolve-source" | "evaluate";
                                /** @enum {string} */
                                status: "pending" | "running" | "done" | "failed";
                                position: number;
                                detail: string | null;
                                startedAt: string | null;
                                finishedAt: string | null;
                            }[];
                            /** @description Null until the evaluate stage completes. */
                            evaluation: {
                                /** @enum {string} */
                                gradation: "try-again" | "needs-work" | "not-bad" | "good-job" | "excellent";
                                label: string;
                                approachSummary: string;
                                missed: string;
                                optimizations: string;
                                model: string | null;
                            } | null;
                            finalGradation: ("try-again" | "needs-work" | "not-bad" | "good-job" | "excellent") | null;
                            overridden: boolean;
                            committedAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/due-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reps due across both flows
         * @description The unified badge count. Broken down by flow so a client can show "3 drills, 2 writeups".
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dueCount: number;
                            /** @description Due cards eligible for the blind drill. */
                            drillDueCount: number;
                            /** @description Due cards graded by note + AI evaluation. */
                            noteDueCount: number;
                            nextDueAt: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything due now, oldest first
         * @description Spans both flows. `mode` is `drill` for curated pattern-tagged problems and `note` for everything else.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                problemId: number;
                                title: string;
                                deckId: number;
                                deckName: string;
                                /** @enum {string} */
                                mode: "drill" | "note";
                                /** Format: date-time */
                                dueAt: string;
                                reps: number;
                                lapses: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The thresholds currently grading this user
         * @description Defaults to the built-in bands (0.8 / 0.55 / 0.3) until this user sets an override.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thresholds: {
                                /** @description Composite at or above this earns Easy. */
                                easy: number;
                                /** @description Composite at or above this earns Good. */
                                good: number;
                                /** @description Composite at or above this earns Hard. Below it, the card lapses (Again). */
                                hard: number;
                            };
                            /** @description True when no override is set, so `thresholds` is just the built-in default. */
                            isDefault: boolean;
                        };
                    };
                };
            };
        };
        /**
         * Set custom thresholds
         * @description Replaces any existing override outright. Must satisfy `hard < good < easy`. Takes effect on the learner's next graded attempt — it does not reschedule cards already due.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Composite at or above this earns Easy. */
                        easy: number;
                        /** @description Composite at or above this earns Good. */
                        good: number;
                        /** @description Composite at or above this earns Hard. Below it, the card lapses (Again). */
                        hard: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thresholds: {
                                /** @description Composite at or above this earns Easy. */
                                easy: number;
                                /** @description Composite at or above this earns Good. */
                                good: number;
                                /** @description Composite at or above this earns Hard. Below it, the card lapses (Again). */
                                hard: number;
                            };
                            /** @description True when no override is set, so `thresholds` is just the built-in default. */
                            isDefault: boolean;
                        };
                    };
                };
                /** @description Something the caller asked for does not exist or is malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Reset to the default thresholds */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thresholds: {
                                /** @description Composite at or above this earns Easy. */
                                easy: number;
                                /** @description Composite at or above this earns Good. */
                                good: number;
                                /** @description Composite at or above this earns Hard. Below it, the card lapses (Again). */
                                hard: number;
                            };
                            /** @description True when no override is set, so `thresholds` is just the built-in default. */
                            isDefault: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
